# Example configuration for hypr-mon-switch
# This file demonstrates the configuration format for different monitor setups

# Global settings
global:
  # Retry settings for monitor detection
  detection:
    max_attempts: 40
    delay: 0.10
  
  # Notification settings
  notifications:
    enabled: true
    timeout: 5000

# Monitor configurations
# Each configuration defines conditions and the resulting monitor layout
configurations:
  # Configuration for two external monitors (laptop disabled) - CHECK FIRST
  - name: "dual-external"
    conditions:
    # if not lif specified it can be either open or closed
      monitors:
        - name: "Samsung"
          connector: "desc:Samsung Electric Company C24FG7x HTHK700065"
        - name: "AOC"
          connector: "desc:AOC 24G2W1G5 0x0000220C"
    layout:
      enabled_monitors:
        - name: "Samsung"
          resolution: "1920x1080@60"
          position: "0x0"
          scale: 1.0
          transform: 0
          workspaces: [1, 2, 3, 4, 5, 6, 7]
        - name: "AOC"
          resolution: "1920x1080@60"
          position: "1920x-420"
          scale: 1.0
          transform: 1
          workspaces: [8, 9, 10]
      disabled_monitors:
        - connector: "desc:BOE 0x0A3A"

  # Configuration for laptop + Samsung (AOC disconnected)
  - name: "laptop-samsung"
    conditions:
      monitors:
        - name: "Samsung"
          connector: "desc:Samsung Electric Company C24FG7x HTHK700065"
        - name: "laptop"
          connector: "desc:BOE 0x0A3A"
    layout:
      enabled_monitors:
        - name: "Samsung"
          resolution: "1920x1080@60"
          position: "0x0"
          scale: 1.0
          transform: 0
          workspaces: [1, 2, 3, 4, 5]
        - name: "laptop"
          resolution: "1920x1200@60"
          position: "1920x0"
          scale: 1.25
          transform: 0
          workspaces: [6, 7, 8, 9, 10]
      disabled_monitors:
        - connector: "desc:AOC 24G2W1G5 0x0000220C"

  # Configuration for dual monitor setup (laptop + external)
  - name: "laptop-external"
    conditions:
      lid_state: "open"
      monitors:
        - name: "Samsung"
          connector: "desc:Samsung Electric Company C24FG7x HTHK700065"
        - name: "laptop"
          connector: "desc:BOE 0x0A3A"
    layout:
      enabled_monitors:
        - name: "Samsung"
          resolution: "1920x1080@60"
          position: "0x0"
          scale: 1.0
          transform: 0
          workspaces: [1, 2, 3, 4, 5]
        - name: "laptop"
          resolution: "1920x1200@60"
          position: "1920x0"
          scale: 1
          transform: 0
          workspaces: [6, 7, 8, 9, 10]
